# Welcome to Mago!
# For full documentation, see https://mago.carthage.software/tools/overview
php-version = "8.2.0"

[source]
paths = ["src/", "tests/"]
includes = ["vendor"]
excludes = [
    "tests/Analyser/Fixtures/PropertyAnalyserClassWithProperties.php",
    "tests/Integration/Fixtures/TestSchemaGeneration/Model/JMS/ComplexObject.php",
]

[formatter]
print-width = 120
tab-width = 4
use-tabs = false

[linter]
integrations = ["psl", "symfony", "phpunit"]

[linter.rules]
literal-named-argument = { enabled = false }
halstead = { volume-threshold = 3_200, effort-threshold = 24_000, difficulty-threshold = 32 }
kan-defect = { enabled = false }
cyclomatic-complexity = { enabled = false }
too-many-methods = { enabled = false }
too-many-properties = { enabled = false }
excessive-parameter-list = { enabled = false }
no-boolean-flag-parameter = { enabled = false }
no-else-clause = { enabled = false }
prefer-early-continue = { enabled = false }
class-name = { enabled = false }
interface-name = { enabled = false }
trait-name = { enabled = false }
yoda-conditions = { enabled = false }
assertion-style = { style = "self" }
psl-array-functions = { enabled = false }
psl-datetime = { enabled = false }
psl-string-functions = { enabled = false }

[analyzer]
find-unused-definitions = true
analyze-dead-code = true
check-throws = true
allow-possibly-undefined-array-keys = true
perform-heuristic-checks = true

# Ignore a specific error code across the whole project
ignore = [
    "unhandled-thrown-type",
    "excess-template-parameter",
    "mixed-argument",
    "invalid-argument",
    "invalid-property-access",
    "mixed-assignment",
    "impossible-assignment",
    "non-existent-class",
    "mixed-array-access",
    "mixed-return-statement",
    "missing-magic-method",
    "possibly-invalid-argument",
    "property-type-coercion",
    "redundant-condition",
    "mixed-property-type-coercion",
    "redundant-type-comparison",
    "non-existent-method",
    "possibly-false-argument",
    "invalid-type-cast",
    "possibly-static-access-on-interface",
    "possibly-null-argument",
    "mixed-operand",
    "possibly-null-array-index",
    "impossible-condition",
    "unknown-match-subject-type",
    "less-specific-nested-argument-type",
    "less-specific-return-statement",
    "less-specific-argument",
    "invalid-operand",
    "redundant-logical-operation",
    "redundant-comparison",
    "impossible-null-type-comparison",
]
