variant = "loose"

[[issues]]
file = "src/Describer/Form/SymfonyValidatorRequirementsDescriber.php"
code = "mixed-property-type-coercion"
message = "A value with a less specific type `nonnull` is being assigned to property `$$maxItems` (int)."
count = 1

[[issues]]
file = "src/Describer/Form/SymfonyValidatorRequirementsDescriber.php"
code = "mixed-property-type-coercion"
message = "A value with a less specific type `nonnull` is being assigned to property `$$maxLength` (int)."
count = 1

[[issues]]
file = "src/Describer/Form/SymfonyValidatorRequirementsDescriber.php"
code = "mixed-property-type-coercion"
message = "A value with a less specific type `nonnull` is being assigned to property `$$maxProperties` (int)."
count = 1

[[issues]]
file = "src/Describer/Form/SymfonyValidatorRequirementsDescriber.php"
code = "mixed-property-type-coercion"
message = "A value with a less specific type `nonnull` is being assigned to property `$$minItems` (int)."
count = 1

[[issues]]
file = "src/Describer/Form/SymfonyValidatorRequirementsDescriber.php"
code = "mixed-property-type-coercion"
message = "A value with a less specific type `nonnull` is being assigned to property `$$minLength` (int)."
count = 1

[[issues]]
file = "src/Describer/Form/SymfonyValidatorRequirementsDescriber.php"
code = "mixed-property-type-coercion"
message = "A value with a less specific type `nonnull` is being assigned to property `$$minProperties` (int)."
count = 1

[[issues]]
file = "tests/Integration/Fixtures/TestSchemaGeneration/Model/JMS/ComplexObjectExampleBuilder.php"
code = "never-return"
message = "Cannot return value with type 'never' from this function."
count = 1
