[[entries."src/Describer/Form/SymfonyValidatorRequirementsDescriber.php".issues]]
code = "mixed-property-type-coercion"
start_line = 180
end_line = 180

[[entries."src/Describer/Form/SymfonyValidatorRequirementsDescriber.php".issues]]
code = "mixed-property-type-coercion"
start_line = 184
end_line = 184

[[entries."src/Describer/Form/SymfonyValidatorRequirementsDescriber.php".issues]]
code = "mixed-property-type-coercion"
start_line = 190
end_line = 190

[[entries."src/Describer/Form/SymfonyValidatorRequirementsDescriber.php".issues]]
code = "mixed-property-type-coercion"
start_line = 194
end_line = 194

[[entries."src/Describer/Form/SymfonyValidatorRequirementsDescriber.php".issues]]
code = "mixed-property-type-coercion"
start_line = 210
end_line = 210

[[entries."src/Describer/Form/SymfonyValidatorRequirementsDescriber.php".issues]]
code = "mixed-property-type-coercion"
start_line = 214
end_line = 214

[[entries."tests/Integration/Fixtures/TestSchemaGeneration/Model/JMS/ComplexObjectExampleBuilder.php".issues]]
code = "never-return"
start_line = 23
end_line = 23
